version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Dependencies.......
      - cd countdown-timer-app
      - npm ci 

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo Uploading To S3 Bucket......
      - aws s3 sync build/ s3://mystaticwebsitestack2-mystaticwebsite-oausntolahmt --delete
      - echo Invalidating CloudFront cache....
      - aws cloudfront create-invalidation --distribution-id E13GUPO44IJ5WG --paths "/*"

artifacts:
  base-directory: countdown-timer-app/build
  files:
    - '**/*'


